name: Checks

on:
  push:

jobs:
  run-linter:
    name: "Run linter"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
  run-tests:
    name: "Run tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: go test ./... -v
  run-example:
    name: "Run example"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: go tool go-e2e -vv
        working-directory: example
      - run: go run main.go -vv
        working-directory: example
