name: Checks

on:
  push:

jobs:
  run-linter:
    name: "Run linter"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
  run-tests:
    name: "Run tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: go test ./... -v
  run-example:
    name: "Run example"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run simple-passing example
        run: go tool go-e2e -vv
        working-directory: examples/simple-passing
      - name: Run simple-failing example
        run: |
          if go tool go-e2e -vv; then
            echo "Expected test to fail but it passed"
            exit 1
          fi
        working-directory: examples/simple-failing
